name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
   name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Lint
        run: |-
          yarn format:check;
          yarn lint;

      - name: Test
        run: |-
          yarn test:unit;
          yarn test:types;

      - name: Build # Tests to see if a build can succeed
        run: yarn build